; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

; === Serial monitor settings for stable USB-CDC on ESP32-C3 ===
; Фиксируем порт и скорость монитора, а также держим RTS/DTR неактивными,
; чтобы избежать автосбросов/дёрганий порта при логировании через USB-JTAG/Serial.
;monitor_port = /dev/cu.usbmodem2101
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
